;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                               ;
;  ######################### HSCRIPTS ########################  ;
;  #                                                         #  ;
;  # HScripts determine how the menu will work/be displayed. #  ;
;  #        You can insert hscript into a section via:       #  ;
;  #                     "HX = pathToHX"                     #  ;
;  #                                                         #  ;
;  # If you have no custom HScript, then just use "default." #  ;
;  #       Hscript can end in .hx, .hxs, or .hscript.        #  ;
;  #                                                         #  ;
;  #                                                         #  ;
;  #                                                         #  ;
;  # ################ CUSTOM HSCRIPT ASSETS ################ #  ;
;  #   If you have custom HScript assets, then you can add   #  ;
;  #  Them into the section that respective to the HScript.  #  ;
;  #      For example, if you have a Main Menu asset and     #  ;
;  # you want to use it in the HScript, you would add this:  #  ;
;  #                                                         #  ;
;  #         "customAsset = path/to/funny/asset.png"         #  ;
;  #          So your section would look like this:          #  ;
;  #                                                         #  ;
;  #                       [Main-Menu]                       #  ;
;  #                       HX = default                      #  ;
;  #            logo = menus/main-menu/logo-pl.png           #  ;
;  #          customAsset = path/to/funny/asset.png          #  ;
;  #                                                         #  ;
;  #        To use them in the HScript, you can use:         #  ;
;  #                                                         #  ;
;  # "ScriptUtils.getThemeAsset('sectionName', 'assetName')" #  ;
;  #                                                         #  ;
;  # For example, in order to get that custom asset that we  #  ;
;  #         Made earlier, then all we would do is:          #  ;
;  #                                                         #  ;
;  # "ScriptUtils.getThemeAsset('Main-Menu', 'customAsset')" #  ;
;  #                                                         #  ;
;  #      And it would return "path/to/funny/asset.png"      #  ;
;  #     That is because the the "customAsset" key in the    #  ;
;  #   default theme which is in the "Main-Menu" section is  #  ;
;  #    set to the logos path within the "Default" theme.    #  ;
;  #                                                         #  ;
;  #                                                         #  ;
;  # ############## GAMEPLAY THEME COMPONENTS ############## #  ;
;  #                                                         #  ;
;  # If a map doesn't disable the option to load the current #  ;
;  #    themes background, then it will default to loading   #  ;
;  #     the BG-HX inside of the current themes ini file.    #  ;
;  #     This HX File will determine the graphics of the     #  ;
;  #        *REPEATING* background of the current map.       #  ;
;  #                                                         #  ;
;  # If a map doesn't disable the option to load the current #  ;
;  #    themes custom hud, then it will default to loading   #  ;
;  #    the HUD-HX inside of the current themes ini file.    #  ;
;  #     This HX File will determine the graphics of the     #  ;
;  #                 hud of the current map.                 #  ;
;  #                                                         #  ;
;  ###########################################################  ;
;                                                               ;
;                                                               ;
;  ###################### THINGS TO NOTE #####################  ;
;  #                                                         #  ;
;  # If an asset is a different resolution than the original #  ;
;  # asset, there is a chance that it isn't positioned/sized #  ;
;  # properly. In that case, you would need to make a new HX #  ;
;  #                to adjust those manually.                #  ;
;  #                                                         #  ;
;  # ###################### FUN FACTS ###################### #  ;
;  #        This game was created in the same language       #  ;
;  #         that you would use to make custom scripts.      #  ;
;  #                                                         #  ;
;  #              HScript stands for HaxeScript.             #  ;
;  #              (This game was made in Haxe!!)             #  ;
;  #                                                         #  ;
;  #  If you really wanted to, you can make your own menus,  #  ;
;  #   and even make a whole game inside the same scripting  #  ;
;  #   language that you use to make these custom menus; I   #  ;
;  #    would like to see someone actually do that now ;)    #  ;
;  #                                                         #  ;
;  ###########################################################  ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


[Global Assets]
key-press = general-sound/key_press.ogg
key-cancel = general-sound/key_cancel.ogg

[Main Menu]
HX = default
logo = menus/main-menu/logo-pl.png
menu-music = menus/main-menu/sounds/menu_music.ogg

[Map Select Menu]
HX = default
overlay = menus/map-select/overlay.png
sidebar-bottom = menus/map-select/sidebar-bot.png
sidebar-top = menus/map-select/sidebar-top.png
tab = menus/map-select/tab.png

[Fonts]
extenro = fonts/extenro.ttf
extenro-bold = fonts/extenro-bold.ttf
extenro-extrabold = fonts/extenro-extrabold.ttf
fredoka-bold = fonts/fredoka-bold.ttf

[Gameplay Theme Components]
BG-HX = default
HUD-HX = default

[Gameplay]
player-glow = gameplay/player_glow.png
arrow-tile = gameplay/arrow_tile.png
release-tile = gameplay/release_tile.png
hit-sound = gameplay/sounds/hit_sound.ogg

[Misc UI]
transition = misc-ui/transition.png
triangle = misc-ui/triangle.png